### PR TITLE
Adds lewd stuff to the Theatre

### PR DESCRIPTION
**Pull request by ghost**
Because probably somehow WetSkrell bribed NT.

~~now go wild you perverts~~

### CODE REVIEW

**Comment by ghost** [comment]
Looks like I need tools of trade. Closing for now.

**Comment by ghost** [comment]
Okay, let's try this again, but it is _probably_ last time and probably everything is broken.
Beware, that mapmerge did stuff with other... Stuff. Feel free to close.

**Comment by OrbisAnima** [comment]
be prepared, there is a chance this one will need to be redone, due to an update.

also, only exodus 2 should need the modification, I see no reason for the other files to be modified

**Comment by OrbisAnima** [comment]
Very good commit, but closing it due to being included in #37 . Thanks!

**Comment by ghost** [comment]
:ok_hand:

**Pull request closed without merging**
