### PR TITLE
Few pipes tweak

### PR DESCRIPTION
**Pull request by ghost**
(Suggesting to test first, as mapmerge being weird)

### CODE REVIEW

**Comment by ShadowLarkens** [comment]
The changelog file is probably just going to cause problems, we haven't set up the changelog scripts yet.

**Comment by RobotAlice** [comment]
I'd just like to know, uh, what did you change, where, exactly?

**Comment by ghost** [comment]
dreamseeker_2016-11-19_23-37-34
dreamseeker_2016-11-19_23-38-43
Fixed pipes at this locations. Plus removes disposal pipes leftovers.

**Comment by SomeP17** [comment]
Eeeeh to hell with it. If somebody else can make better fix of it - feel free to.

**Pull request merged**
